---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpctk-fastapi
  namespace: the-precast-toolkit-fs
spec:
  selector:
    matchLabels:
      app: tpctk-fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: tpctk-fastapi
    spec:
      containers:
      - name: tpctk-fastapi
        image: milsman2/tpctk-fs-async-backend:0.2
        ports:
        - containerPort: 8000
          name: tpctk-fastapi
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: database_user
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: database_password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: database_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: database_name
      nodeSelector:
        nodeCategory: worker
