apiVersion: v1
kind: Service
metadata:
  name: tpctk-fs-kube-backend
  namespace: the-precast-toolkit-fs
spec:
  ports:
  - port: 8000
    name: tpctk-fs-kube-backend
  selector:
    app: tpctk-fs-kube-backend