apiVersion: v1
kind: Service
metadata:
  name: tpctk-fastapi
  namespace: the-precast-toolkit-fs
spec:
  ports:
  - protocol: TCP
    port: 8000
    name: tpctk-fastapi
  selector:
    app: tpctk-fastapi
