"""no unique Vulcan

Revision ID: 3cfa71e78299
Revises: d53fdabb3475
Create Date: 2022-05-12 00:06:17.855176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfa71e78299'
down_revision = 'd53fdabb3475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cast_iron_Vulcan_style_code_key', 'cast_iron', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cast_iron_Vulcan_style_code_key', 'cast_iron', ['Vulcan_style_code'])
    # ### end Alembic commands ###
