"""schema fix

Revision ID: 4807c74586a3
Revises: e41e671e7715
Create Date: 2022-06-17 02:47:16.900040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4807c74586a3'
down_revision = 'e41e671e7715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
