"""added TPCTK Codes

Revision ID: 738398be639c
Revises: 3cfa71e78299
Create Date: 2022-06-17 02:09:05.363225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738398be639c'
down_revision = '3cfa71e78299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_iron', sa.Column('TPCTK_Code', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast_iron', 'TPCTK_Code')
    # ### end Alembic commands ###
