"""added TPCTK schema

Revision ID: e41e671e7715
Revises: 738398be639c
Create Date: 2022-06-17 02:14:18.869454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41e671e7715'
down_revision = '738398be639c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
