apiVersion: v2
name: tpctk-fs-mysql
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: mysql
  version: 8.9.6
  repository: https://charts.bitnami.com/bitnami