mysql:
  global:
    storageClass: "longhorn"
  image:
    registry: docker.io
    repository: bitnami/mysql
    tag: 8.0.29-debian-10-r15
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    database: tpctk-fs-mysql
    username: "tpctkfsmysqluser"
    replicationUser: tpctckfsreplicator
    existingSecret: "mysql-secret"
    forcePassword: true
    usePasswordFiles: false
  nodeSelector:
    nodeCategory: worker
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  persistence:
    enabled: true
    storageClass: "longhorn"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  service:
    type: ClusterIP
    port: 3306
    externalTrafficPolicy: Cluster
  pdb:
    enabled: false
  serviceAccount:
    create: true
  rbac:
    create: false
  networkPolicy:
    enabled: false
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 10-debian-10-r409
      pullPolicy: IfNotPresent
  metrics:
    enabled: false
